name: Generate snake

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ammar-zahid
          output_file: snake.svg
